/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LiveDemoRouteImport } from './routes/live-demo'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WalkthroughRouteImport } from './routes/walkthrough'
import { Route as CheckoutSessionIdRouteImport } from './routes/checkout.$sessionId'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsApiPricingRouteImport } from './routes/docs.api-pricing'
import { Route as DocsAuthenticationRouteImport } from './routes/docs.authentication'
import { Route as DocsCounterpartiesRouteImport } from './routes/docs.counterparties'
import { Route as DocsErrorsRouteImport } from './routes/docs.errors'
import { Route as DocsEvidenceRouteImport } from './routes/docs.evidence'
import { Route as DocsMatchesRouteImport } from './routes/docs.matches'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsWebhooksRouteImport } from './routes/docs.webhooks'
import { Route as HqIndexRouteImport } from './routes/hq.index'
import { Route as HqAiSuggestionsRouteImport } from './routes/hq.ai-suggestions'
import { Route as HqAuditRouteImport } from './routes/hq.audit'
import { Route as HqComplianceRouteImport } from './routes/hq.compliance'
import { Route as HqDisputesRouteImport } from './routes/hq.disputes'
import { Route as HqEngagementsRouteImport } from './routes/hq.engagements'
import { Route as HqExecutionCasesRouteImport } from './routes/hq.execution-cases'
import { Route as HqFacilitationRouteImport } from './routes/hq.facilitation'
import { Route as HqFunderWorkflowRouteImport } from './routes/hq.funder-workflow'
import { Route as HqGovernanceRouteImport } from './routes/hq.governance'
import { Route as HqGovernanceRecordsRouteImport } from './routes/hq.governance-records'
import { Route as HqIdentityRouteImport } from './routes/hq.identity'
import { Route as HqIdvRouteImport } from './routes/hq.idv'
import { Route as HqLegacyRepairRouteImport } from './routes/hq.legacy-repair'
import { Route as HqLegalHoldsRouteImport } from './routes/hq.legal-holds'
import { Route as HqOrganisationsRouteImport } from './routes/hq.organisations'
import { Route as HqRevenueRouteImport } from './routes/hq.revenue'
import { Route as HqSettingsRouteImport } from './routes/hq.settings'
import { Route as HqSystemHealthRouteImport } from './routes/hq.system-health'
import { Route as HqUsersRouteImport } from './routes/hq.users'
import { Route as ProductsAuditLedgerRouteImport } from './routes/products.audit-ledger'
import { Route as ProductsComplianceEngineRouteImport } from './routes/products.compliance-engine'
import { Route as ProductsTradeDeskRouteImport } from './routes/products.trade-desk'
import { Route as SolutionsFinanceRouteImport } from './routes/solutions.finance'
import { Route as SolutionsSovereignsRouteImport } from './routes/solutions.sovereigns'
import { Route as SolutionsTradersRouteImport } from './routes/solutions.traders'
import { Route as HqFunderIndexRouteImport } from './routes/hq.funder.index'
import { Route as HqFunderAuditRouteImport } from './routes/hq.funder.audit'
import { Route as HqFunderOnboardingRouteImport } from './routes/hq.funder.onboarding'
import { Route as HqFunderOrganisationsRouteImport } from './routes/hq.funder.organisations'
import { Route as HqFunderReleasesRouteImport } from './routes/hq.funder.releases'
import { Route as HqRegistryIndexRouteImport } from './routes/hq.registry.index'
import { Route as HqRegistryApiClientsRouteImport } from './routes/hq.registry.api-clients'
import { Route as HqRegistryApiUsageRouteImport } from './routes/hq.registry.api-usage'
import { Route as HqRegistryBankVerificationRouteImport } from './routes/hq.registry.bank-verification'
import { Route as HqRegistryClaimsRouteImport } from './routes/hq.registry.claims'
import { Route as HqRegistryOperationsRouteImport } from './routes/hq.registry.operations'
import { Route as HqRegistryRecordsRouteImport } from './routes/hq.registry.records'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemoRoute = LiveDemoRouteImport.update({
  id: '/live-demo',
  path: '/live-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkthroughRoute = WalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSessionIdRoute = CheckoutSessionIdRouteImport.update({
  id: '/checkout/$sessionId',
  path: '/checkout/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiPricingRoute = DocsApiPricingRouteImport.update({
  id: '/docs/api-pricing',
  path: '/docs/api-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAuthenticationRoute = DocsAuthenticationRouteImport.update({
  id: '/docs/authentication',
  path: '/docs/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCounterpartiesRoute = DocsCounterpartiesRouteImport.update({
  id: '/docs/counterparties',
  path: '/docs/counterparties',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: '/docs/errors',
  path: '/docs/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsEvidenceRoute = DocsEvidenceRouteImport.update({
  id: '/docs/evidence',
  path: '/docs/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMatchesRoute = DocsMatchesRouteImport.update({
  id: '/docs/matches',
  path: '/docs/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/docs/quickstart',
  path: '/docs/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWebhooksRoute = DocsWebhooksRouteImport.update({
  id: '/docs/webhooks',
  path: '/docs/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const HqIndexRoute = HqIndexRouteImport.update({
  id: '/hq/',
  path: '/hq/',
  getParentRoute: () => rootRouteImport,
} as any)
const HqAiSuggestionsRoute = HqAiSuggestionsRouteImport.update({
  id: '/hq/ai-suggestions',
  path: '/hq/ai-suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const HqAuditRoute = HqAuditRouteImport.update({
  id: '/hq/audit',
  path: '/hq/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const HqComplianceRoute = HqComplianceRouteImport.update({
  id: '/hq/compliance',
  path: '/hq/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const HqDisputesRoute = HqDisputesRouteImport.update({
  id: '/hq/disputes',
  path: '/hq/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const HqEngagementsRoute = HqEngagementsRouteImport.update({
  id: '/hq/engagements',
  path: '/hq/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const HqExecutionCasesRoute = HqExecutionCasesRouteImport.update({
  id: '/hq/execution-cases',
  path: '/hq/execution-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const HqFacilitationRoute = HqFacilitationRouteImport.update({
  id: '/hq/facilitation',
  path: '/hq/facilitation',
  getParentRoute: () => rootRouteImport,
} as any)
const HqFunderWorkflowRoute = HqFunderWorkflowRouteImport.update({
  id: '/hq/funder-workflow',
  path: '/hq/funder-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const HqGovernanceRoute = HqGovernanceRouteImport.update({
  id: '/hq/governance',
  path: '/hq/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const HqGovernanceRecordsRoute = HqGovernanceRecordsRouteImport.update({
  id: '/hq/governance-records',
  path: '/hq/governance-records',
  getParentRoute: () => rootRouteImport,
} as any)
const HqIdentityRoute = HqIdentityRouteImport.update({
  id: '/hq/identity',
  path: '/hq/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const HqIdvRoute = HqIdvRouteImport.update({
  id: '/hq/idv',
  path: '/hq/idv',
  getParentRoute: () => rootRouteImport,
} as any)
const HqLegacyRepairRoute = HqLegacyRepairRouteImport.update({
  id: '/hq/legacy-repair',
  path: '/hq/legacy-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const HqLegalHoldsRoute = HqLegalHoldsRouteImport.update({
  id: '/hq/legal-holds',
  path: '/hq/legal-holds',
  getParentRoute: () => rootRouteImport,
} as any)
const HqOrganisationsRoute = HqOrganisationsRouteImport.update({
  id: '/hq/organisations',
  path: '/hq/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRevenueRoute = HqRevenueRouteImport.update({
  id: '/hq/revenue',
  path: '/hq/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const HqSettingsRoute = HqSettingsRouteImport.update({
  id: '/hq/settings',
  path: '/hq/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HqSystemHealthRoute = HqSystemHealthRouteImport.update({
  id: '/hq/system-health',
  path: '/hq/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const HqUsersRoute = HqUsersRouteImport.update({
  id: '/hq/users',
  path: '/hq/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAuditLedgerRoute = ProductsAuditLedgerRouteImport.update({
  id: '/products/audit-ledger',
  path: '/products/audit-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsComplianceEngineRoute =
  ProductsComplianceEngineRouteImport.update({
    id: '/products/compliance-engine',
    path: '/products/compliance-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsTradeDeskRoute = ProductsTradeDeskRouteImport.update({
  id: '/products/trade-desk',
  path: '/products/trade-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFinanceRoute = SolutionsFinanceRouteImport.update({
  id: '/solutions/finance',
  path: '/solutions/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSovereignsRoute = SolutionsSovereignsRouteImport.update({
  id: '/solutions/sovereigns',
  path: '/solutions/sovereigns',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTradersRoute = SolutionsTradersRouteImport.update({
  id: '/solutions/traders',
  path: '/solutions/traders',
  getParentRoute: () => rootRouteImport,
} as any)
const HqFunderIndexRoute = HqFunderIndexRouteImport.update({
  id: '/hq/funder/',
  path: '/hq/funder/',
  getParentRoute: () => rootRouteImport,
} as any)
const HqFunderAuditRoute = HqFunderAuditRouteImport.update({
  id: '/hq/funder/audit',
  path: '/hq/funder/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const HqFunderOnboardingRoute = HqFunderOnboardingRouteImport.update({
  id: '/hq/funder/onboarding',
  path: '/hq/funder/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HqFunderOrganisationsRoute = HqFunderOrganisationsRouteImport.update({
  id: '/hq/funder/organisations',
  path: '/hq/funder/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const HqFunderReleasesRoute = HqFunderReleasesRouteImport.update({
  id: '/hq/funder/releases',
  path: '/hq/funder/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRegistryIndexRoute = HqRegistryIndexRouteImport.update({
  id: '/hq/registry/',
  path: '/hq/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRegistryApiClientsRoute = HqRegistryApiClientsRouteImport.update({
  id: '/hq/registry/api-clients',
  path: '/hq/registry/api-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRegistryApiUsageRoute = HqRegistryApiUsageRouteImport.update({
  id: '/hq/registry/api-usage',
  path: '/hq/registry/api-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRegistryBankVerificationRoute =
  HqRegistryBankVerificationRouteImport.update({
    id: '/hq/registry/bank-verification',
    path: '/hq/registry/bank-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const HqRegistryClaimsRoute = HqRegistryClaimsRouteImport.update({
  id: '/hq/registry/claims',
  path: '/hq/registry/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRegistryOperationsRoute = HqRegistryOperationsRouteImport.update({
  id: '/hq/registry/operations',
  path: '/hq/registry/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRegistryRecordsRoute = HqRegistryRecordsRouteImport.update({
  id: '/hq/registry/records',
  path: '/hq/registry/records',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/walkthrough': typeof WalkthroughRoute
  '/checkout/$sessionId': typeof CheckoutSessionIdRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/api-pricing': typeof DocsApiPricingRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/counterparties': typeof DocsCounterpartiesRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/evidence': typeof DocsEvidenceRoute
  '/docs/matches': typeof DocsMatchesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/hq/ai-suggestions': typeof HqAiSuggestionsRoute
  '/hq/audit': typeof HqAuditRoute
  '/hq/compliance': typeof HqComplianceRoute
  '/hq/disputes': typeof HqDisputesRoute
  '/hq/engagements': typeof HqEngagementsRoute
  '/hq/execution-cases': typeof HqExecutionCasesRoute
  '/hq/facilitation': typeof HqFacilitationRoute
  '/hq/funder-workflow': typeof HqFunderWorkflowRoute
  '/hq/governance': typeof HqGovernanceRoute
  '/hq/governance-records': typeof HqGovernanceRecordsRoute
  '/hq/identity': typeof HqIdentityRoute
  '/hq/idv': typeof HqIdvRoute
  '/hq/legacy-repair': typeof HqLegacyRepairRoute
  '/hq/legal-holds': typeof HqLegalHoldsRoute
  '/hq/organisations': typeof HqOrganisationsRoute
  '/hq/revenue': typeof HqRevenueRoute
  '/hq/settings': typeof HqSettingsRoute
  '/hq/system-health': typeof HqSystemHealthRoute
  '/hq/users': typeof HqUsersRoute
  '/products/audit-ledger': typeof ProductsAuditLedgerRoute
  '/products/compliance-engine': typeof ProductsComplianceEngineRoute
  '/products/trade-desk': typeof ProductsTradeDeskRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/sovereigns': typeof SolutionsSovereignsRoute
  '/solutions/traders': typeof SolutionsTradersRoute
  '/docs/': typeof DocsIndexRoute
  '/hq/': typeof HqIndexRoute
  '/hq/funder/audit': typeof HqFunderAuditRoute
  '/hq/funder/onboarding': typeof HqFunderOnboardingRoute
  '/hq/funder/organisations': typeof HqFunderOrganisationsRoute
  '/hq/funder/releases': typeof HqFunderReleasesRoute
  '/hq/registry/api-clients': typeof HqRegistryApiClientsRoute
  '/hq/registry/api-usage': typeof HqRegistryApiUsageRoute
  '/hq/registry/bank-verification': typeof HqRegistryBankVerificationRoute
  '/hq/registry/claims': typeof HqRegistryClaimsRoute
  '/hq/registry/operations': typeof HqRegistryOperationsRoute
  '/hq/registry/records': typeof HqRegistryRecordsRoute
  '/hq/funder/': typeof HqFunderIndexRoute
  '/hq/registry/': typeof HqRegistryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/walkthrough': typeof WalkthroughRoute
  '/checkout/$sessionId': typeof CheckoutSessionIdRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/api-pricing': typeof DocsApiPricingRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/counterparties': typeof DocsCounterpartiesRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/evidence': typeof DocsEvidenceRoute
  '/docs/matches': typeof DocsMatchesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/hq/ai-suggestions': typeof HqAiSuggestionsRoute
  '/hq/audit': typeof HqAuditRoute
  '/hq/compliance': typeof HqComplianceRoute
  '/hq/disputes': typeof HqDisputesRoute
  '/hq/engagements': typeof HqEngagementsRoute
  '/hq/execution-cases': typeof HqExecutionCasesRoute
  '/hq/facilitation': typeof HqFacilitationRoute
  '/hq/funder-workflow': typeof HqFunderWorkflowRoute
  '/hq/governance': typeof HqGovernanceRoute
  '/hq/governance-records': typeof HqGovernanceRecordsRoute
  '/hq/identity': typeof HqIdentityRoute
  '/hq/idv': typeof HqIdvRoute
  '/hq/legacy-repair': typeof HqLegacyRepairRoute
  '/hq/legal-holds': typeof HqLegalHoldsRoute
  '/hq/organisations': typeof HqOrganisationsRoute
  '/hq/revenue': typeof HqRevenueRoute
  '/hq/settings': typeof HqSettingsRoute
  '/hq/system-health': typeof HqSystemHealthRoute
  '/hq/users': typeof HqUsersRoute
  '/products/audit-ledger': typeof ProductsAuditLedgerRoute
  '/products/compliance-engine': typeof ProductsComplianceEngineRoute
  '/products/trade-desk': typeof ProductsTradeDeskRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/sovereigns': typeof SolutionsSovereignsRoute
  '/solutions/traders': typeof SolutionsTradersRoute
  '/docs': typeof DocsIndexRoute
  '/hq': typeof HqIndexRoute
  '/hq/funder/audit': typeof HqFunderAuditRoute
  '/hq/funder/onboarding': typeof HqFunderOnboardingRoute
  '/hq/funder/organisations': typeof HqFunderOrganisationsRoute
  '/hq/funder/releases': typeof HqFunderReleasesRoute
  '/hq/registry/api-clients': typeof HqRegistryApiClientsRoute
  '/hq/registry/api-usage': typeof HqRegistryApiUsageRoute
  '/hq/registry/bank-verification': typeof HqRegistryBankVerificationRoute
  '/hq/registry/claims': typeof HqRegistryClaimsRoute
  '/hq/registry/operations': typeof HqRegistryOperationsRoute
  '/hq/registry/records': typeof HqRegistryRecordsRoute
  '/hq/funder': typeof HqFunderIndexRoute
  '/hq/registry': typeof HqRegistryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/walkthrough': typeof WalkthroughRoute
  '/checkout/$sessionId': typeof CheckoutSessionIdRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/api-pricing': typeof DocsApiPricingRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/counterparties': typeof DocsCounterpartiesRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/evidence': typeof DocsEvidenceRoute
  '/docs/matches': typeof DocsMatchesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/hq/ai-suggestions': typeof HqAiSuggestionsRoute
  '/hq/audit': typeof HqAuditRoute
  '/hq/compliance': typeof HqComplianceRoute
  '/hq/disputes': typeof HqDisputesRoute
  '/hq/engagements': typeof HqEngagementsRoute
  '/hq/execution-cases': typeof HqExecutionCasesRoute
  '/hq/facilitation': typeof HqFacilitationRoute
  '/hq/funder-workflow': typeof HqFunderWorkflowRoute
  '/hq/governance': typeof HqGovernanceRoute
  '/hq/governance-records': typeof HqGovernanceRecordsRoute
  '/hq/identity': typeof HqIdentityRoute
  '/hq/idv': typeof HqIdvRoute
  '/hq/legacy-repair': typeof HqLegacyRepairRoute
  '/hq/legal-holds': typeof HqLegalHoldsRoute
  '/hq/organisations': typeof HqOrganisationsRoute
  '/hq/revenue': typeof HqRevenueRoute
  '/hq/settings': typeof HqSettingsRoute
  '/hq/system-health': typeof HqSystemHealthRoute
  '/hq/users': typeof HqUsersRoute
  '/products/audit-ledger': typeof ProductsAuditLedgerRoute
  '/products/compliance-engine': typeof ProductsComplianceEngineRoute
  '/products/trade-desk': typeof ProductsTradeDeskRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/sovereigns': typeof SolutionsSovereignsRoute
  '/solutions/traders': typeof SolutionsTradersRoute
  '/docs/': typeof DocsIndexRoute
  '/hq/': typeof HqIndexRoute
  '/hq/funder/audit': typeof HqFunderAuditRoute
  '/hq/funder/onboarding': typeof HqFunderOnboardingRoute
  '/hq/funder/organisations': typeof HqFunderOrganisationsRoute
  '/hq/funder/releases': typeof HqFunderReleasesRoute
  '/hq/registry/api-clients': typeof HqRegistryApiClientsRoute
  '/hq/registry/api-usage': typeof HqRegistryApiUsageRoute
  '/hq/registry/bank-verification': typeof HqRegistryBankVerificationRoute
  '/hq/registry/claims': typeof HqRegistryClaimsRoute
  '/hq/registry/operations': typeof HqRegistryOperationsRoute
  '/hq/registry/records': typeof HqRegistryRecordsRoute
  '/hq/funder/': typeof HqFunderIndexRoute
  '/hq/registry/': typeof HqRegistryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/live-demo'
    | '/pricing'
    | '/reset-password'
    | '/status'
    | '/trust'
    | '/walkthrough'
    | '/checkout/$sessionId'
    | '/docs/api'
    | '/docs/api-pricing'
    | '/docs/authentication'
    | '/docs/counterparties'
    | '/docs/errors'
    | '/docs/evidence'
    | '/docs/matches'
    | '/docs/quickstart'
    | '/docs/webhooks'
    | '/hq/ai-suggestions'
    | '/hq/audit'
    | '/hq/compliance'
    | '/hq/disputes'
    | '/hq/engagements'
    | '/hq/execution-cases'
    | '/hq/facilitation'
    | '/hq/funder-workflow'
    | '/hq/governance'
    | '/hq/governance-records'
    | '/hq/identity'
    | '/hq/idv'
    | '/hq/legacy-repair'
    | '/hq/legal-holds'
    | '/hq/organisations'
    | '/hq/revenue'
    | '/hq/settings'
    | '/hq/system-health'
    | '/hq/users'
    | '/products/audit-ledger'
    | '/products/compliance-engine'
    | '/products/trade-desk'
    | '/solutions/finance'
    | '/solutions/sovereigns'
    | '/solutions/traders'
    | '/docs/'
    | '/hq/'
    | '/hq/funder/audit'
    | '/hq/funder/onboarding'
    | '/hq/funder/organisations'
    | '/hq/funder/releases'
    | '/hq/registry/api-clients'
    | '/hq/registry/api-usage'
    | '/hq/registry/bank-verification'
    | '/hq/registry/claims'
    | '/hq/registry/operations'
    | '/hq/registry/records'
    | '/hq/funder/'
    | '/hq/registry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/live-demo'
    | '/pricing'
    | '/reset-password'
    | '/status'
    | '/trust'
    | '/walkthrough'
    | '/checkout/$sessionId'
    | '/docs/api'
    | '/docs/api-pricing'
    | '/docs/authentication'
    | '/docs/counterparties'
    | '/docs/errors'
    | '/docs/evidence'
    | '/docs/matches'
    | '/docs/quickstart'
    | '/docs/webhooks'
    | '/hq/ai-suggestions'
    | '/hq/audit'
    | '/hq/compliance'
    | '/hq/disputes'
    | '/hq/engagements'
    | '/hq/execution-cases'
    | '/hq/facilitation'
    | '/hq/funder-workflow'
    | '/hq/governance'
    | '/hq/governance-records'
    | '/hq/identity'
    | '/hq/idv'
    | '/hq/legacy-repair'
    | '/hq/legal-holds'
    | '/hq/organisations'
    | '/hq/revenue'
    | '/hq/settings'
    | '/hq/system-health'
    | '/hq/users'
    | '/products/audit-ledger'
    | '/products/compliance-engine'
    | '/products/trade-desk'
    | '/solutions/finance'
    | '/solutions/sovereigns'
    | '/solutions/traders'
    | '/docs'
    | '/hq'
    | '/hq/funder/audit'
    | '/hq/funder/onboarding'
    | '/hq/funder/organisations'
    | '/hq/funder/releases'
    | '/hq/registry/api-clients'
    | '/hq/registry/api-usage'
    | '/hq/registry/bank-verification'
    | '/hq/registry/claims'
    | '/hq/registry/operations'
    | '/hq/registry/records'
    | '/hq/funder'
    | '/hq/registry'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/live-demo'
    | '/pricing'
    | '/reset-password'
    | '/status'
    | '/trust'
    | '/walkthrough'
    | '/checkout/$sessionId'
    | '/docs/api'
    | '/docs/api-pricing'
    | '/docs/authentication'
    | '/docs/counterparties'
    | '/docs/errors'
    | '/docs/evidence'
    | '/docs/matches'
    | '/docs/quickstart'
    | '/docs/webhooks'
    | '/hq/ai-suggestions'
    | '/hq/audit'
    | '/hq/compliance'
    | '/hq/disputes'
    | '/hq/engagements'
    | '/hq/execution-cases'
    | '/hq/facilitation'
    | '/hq/funder-workflow'
    | '/hq/governance'
    | '/hq/governance-records'
    | '/hq/identity'
    | '/hq/idv'
    | '/hq/legacy-repair'
    | '/hq/legal-holds'
    | '/hq/organisations'
    | '/hq/revenue'
    | '/hq/settings'
    | '/hq/system-health'
    | '/hq/users'
    | '/products/audit-ledger'
    | '/products/compliance-engine'
    | '/products/trade-desk'
    | '/solutions/finance'
    | '/solutions/sovereigns'
    | '/solutions/traders'
    | '/docs/'
    | '/hq/'
    | '/hq/funder/audit'
    | '/hq/funder/onboarding'
    | '/hq/funder/organisations'
    | '/hq/funder/releases'
    | '/hq/registry/api-clients'
    | '/hq/registry/api-usage'
    | '/hq/registry/bank-verification'
    | '/hq/registry/claims'
    | '/hq/registry/operations'
    | '/hq/registry/records'
    | '/hq/funder/'
    | '/hq/registry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveDemoRoute: typeof LiveDemoRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatusRoute: typeof StatusRoute
  TrustRoute: typeof TrustRoute
  WalkthroughRoute: typeof WalkthroughRoute
  CheckoutSessionIdRoute: typeof CheckoutSessionIdRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsApiPricingRoute: typeof DocsApiPricingRoute
  DocsAuthenticationRoute: typeof DocsAuthenticationRoute
  DocsCounterpartiesRoute: typeof DocsCounterpartiesRoute
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsEvidenceRoute: typeof DocsEvidenceRoute
  DocsMatchesRoute: typeof DocsMatchesRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsWebhooksRoute: typeof DocsWebhooksRoute
  HqAiSuggestionsRoute: typeof HqAiSuggestionsRoute
  HqAuditRoute: typeof HqAuditRoute
  HqComplianceRoute: typeof HqComplianceRoute
  HqDisputesRoute: typeof HqDisputesRoute
  HqEngagementsRoute: typeof HqEngagementsRoute
  HqExecutionCasesRoute: typeof HqExecutionCasesRoute
  HqFacilitationRoute: typeof HqFacilitationRoute
  HqFunderWorkflowRoute: typeof HqFunderWorkflowRoute
  HqGovernanceRoute: typeof HqGovernanceRoute
  HqGovernanceRecordsRoute: typeof HqGovernanceRecordsRoute
  HqIdentityRoute: typeof HqIdentityRoute
  HqIdvRoute: typeof HqIdvRoute
  HqLegacyRepairRoute: typeof HqLegacyRepairRoute
  HqLegalHoldsRoute: typeof HqLegalHoldsRoute
  HqOrganisationsRoute: typeof HqOrganisationsRoute
  HqRevenueRoute: typeof HqRevenueRoute
  HqSettingsRoute: typeof HqSettingsRoute
  HqSystemHealthRoute: typeof HqSystemHealthRoute
  HqUsersRoute: typeof HqUsersRoute
  ProductsAuditLedgerRoute: typeof ProductsAuditLedgerRoute
  ProductsComplianceEngineRoute: typeof ProductsComplianceEngineRoute
  ProductsTradeDeskRoute: typeof ProductsTradeDeskRoute
  SolutionsFinanceRoute: typeof SolutionsFinanceRoute
  SolutionsSovereignsRoute: typeof SolutionsSovereignsRoute
  SolutionsTradersRoute: typeof SolutionsTradersRoute
  DocsIndexRoute: typeof DocsIndexRoute
  HqIndexRoute: typeof HqIndexRoute
  HqFunderAuditRoute: typeof HqFunderAuditRoute
  HqFunderOnboardingRoute: typeof HqFunderOnboardingRoute
  HqFunderOrganisationsRoute: typeof HqFunderOrganisationsRoute
  HqFunderReleasesRoute: typeof HqFunderReleasesRoute
  HqRegistryApiClientsRoute: typeof HqRegistryApiClientsRoute
  HqRegistryApiUsageRoute: typeof HqRegistryApiUsageRoute
  HqRegistryBankVerificationRoute: typeof HqRegistryBankVerificationRoute
  HqRegistryClaimsRoute: typeof HqRegistryClaimsRoute
  HqRegistryOperationsRoute: typeof HqRegistryOperationsRoute
  HqRegistryRecordsRoute: typeof HqRegistryRecordsRoute
  HqFunderIndexRoute: typeof HqFunderIndexRoute
  HqRegistryIndexRoute: typeof HqRegistryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demo': {
      id: '/live-demo'
      path: '/live-demo'
      fullPath: '/live-demo'
      preLoaderRoute: typeof LiveDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walkthrough': {
      id: '/walkthrough'
      path: '/walkthrough'
      fullPath: '/walkthrough'
      preLoaderRoute: typeof WalkthroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$sessionId': {
      id: '/checkout/$sessionId'
      path: '/checkout/$sessionId'
      fullPath: '/checkout/$sessionId'
      preLoaderRoute: typeof CheckoutSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-pricing': {
      id: '/docs/api-pricing'
      path: '/docs/api-pricing'
      fullPath: '/docs/api-pricing'
      preLoaderRoute: typeof DocsApiPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/authentication': {
      id: '/docs/authentication'
      path: '/docs/authentication'
      fullPath: '/docs/authentication'
      preLoaderRoute: typeof DocsAuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/counterparties': {
      id: '/docs/counterparties'
      path: '/docs/counterparties'
      fullPath: '/docs/counterparties'
      preLoaderRoute: typeof DocsCounterpartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/errors': {
      id: '/docs/errors'
      path: '/docs/errors'
      fullPath: '/docs/errors'
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/evidence': {
      id: '/docs/evidence'
      path: '/docs/evidence'
      fullPath: '/docs/evidence'
      preLoaderRoute: typeof DocsEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/matches': {
      id: '/docs/matches'
      path: '/docs/matches'
      fullPath: '/docs/matches'
      preLoaderRoute: typeof DocsMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/docs/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/webhooks': {
      id: '/docs/webhooks'
      path: '/docs/webhooks'
      fullPath: '/docs/webhooks'
      preLoaderRoute: typeof DocsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/': {
      id: '/hq/'
      path: '/hq'
      fullPath: '/hq/'
      preLoaderRoute: typeof HqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/ai-suggestions': {
      id: '/hq/ai-suggestions'
      path: '/hq/ai-suggestions'
      fullPath: '/hq/ai-suggestions'
      preLoaderRoute: typeof HqAiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/audit': {
      id: '/hq/audit'
      path: '/hq/audit'
      fullPath: '/hq/audit'
      preLoaderRoute: typeof HqAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/compliance': {
      id: '/hq/compliance'
      path: '/hq/compliance'
      fullPath: '/hq/compliance'
      preLoaderRoute: typeof HqComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/disputes': {
      id: '/hq/disputes'
      path: '/hq/disputes'
      fullPath: '/hq/disputes'
      preLoaderRoute: typeof HqDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/engagements': {
      id: '/hq/engagements'
      path: '/hq/engagements'
      fullPath: '/hq/engagements'
      preLoaderRoute: typeof HqEngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/execution-cases': {
      id: '/hq/execution-cases'
      path: '/hq/execution-cases'
      fullPath: '/hq/execution-cases'
      preLoaderRoute: typeof HqExecutionCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/facilitation': {
      id: '/hq/facilitation'
      path: '/hq/facilitation'
      fullPath: '/hq/facilitation'
      preLoaderRoute: typeof HqFacilitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/funder-workflow': {
      id: '/hq/funder-workflow'
      path: '/hq/funder-workflow'
      fullPath: '/hq/funder-workflow'
      preLoaderRoute: typeof HqFunderWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/governance': {
      id: '/hq/governance'
      path: '/hq/governance'
      fullPath: '/hq/governance'
      preLoaderRoute: typeof HqGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/governance-records': {
      id: '/hq/governance-records'
      path: '/hq/governance-records'
      fullPath: '/hq/governance-records'
      preLoaderRoute: typeof HqGovernanceRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/identity': {
      id: '/hq/identity'
      path: '/hq/identity'
      fullPath: '/hq/identity'
      preLoaderRoute: typeof HqIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/idv': {
      id: '/hq/idv'
      path: '/hq/idv'
      fullPath: '/hq/idv'
      preLoaderRoute: typeof HqIdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/legacy-repair': {
      id: '/hq/legacy-repair'
      path: '/hq/legacy-repair'
      fullPath: '/hq/legacy-repair'
      preLoaderRoute: typeof HqLegacyRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/legal-holds': {
      id: '/hq/legal-holds'
      path: '/hq/legal-holds'
      fullPath: '/hq/legal-holds'
      preLoaderRoute: typeof HqLegalHoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/organisations': {
      id: '/hq/organisations'
      path: '/hq/organisations'
      fullPath: '/hq/organisations'
      preLoaderRoute: typeof HqOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/revenue': {
      id: '/hq/revenue'
      path: '/hq/revenue'
      fullPath: '/hq/revenue'
      preLoaderRoute: typeof HqRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/settings': {
      id: '/hq/settings'
      path: '/hq/settings'
      fullPath: '/hq/settings'
      preLoaderRoute: typeof HqSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/system-health': {
      id: '/hq/system-health'
      path: '/hq/system-health'
      fullPath: '/hq/system-health'
      preLoaderRoute: typeof HqSystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/users': {
      id: '/hq/users'
      path: '/hq/users'
      fullPath: '/hq/users'
      preLoaderRoute: typeof HqUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/audit-ledger': {
      id: '/products/audit-ledger'
      path: '/products/audit-ledger'
      fullPath: '/products/audit-ledger'
      preLoaderRoute: typeof ProductsAuditLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/compliance-engine': {
      id: '/products/compliance-engine'
      path: '/products/compliance-engine'
      fullPath: '/products/compliance-engine'
      preLoaderRoute: typeof ProductsComplianceEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/trade-desk': {
      id: '/products/trade-desk'
      path: '/products/trade-desk'
      fullPath: '/products/trade-desk'
      preLoaderRoute: typeof ProductsTradeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/finance': {
      id: '/solutions/finance'
      path: '/solutions/finance'
      fullPath: '/solutions/finance'
      preLoaderRoute: typeof SolutionsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/sovereigns': {
      id: '/solutions/sovereigns'
      path: '/solutions/sovereigns'
      fullPath: '/solutions/sovereigns'
      preLoaderRoute: typeof SolutionsSovereignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/traders': {
      id: '/solutions/traders'
      path: '/solutions/traders'
      fullPath: '/solutions/traders'
      preLoaderRoute: typeof SolutionsTradersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/funder/': {
      id: '/hq/funder/'
      path: '/hq/funder'
      fullPath: '/hq/funder/'
      preLoaderRoute: typeof HqFunderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/funder/audit': {
      id: '/hq/funder/audit'
      path: '/hq/funder/audit'
      fullPath: '/hq/funder/audit'
      preLoaderRoute: typeof HqFunderAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/funder/onboarding': {
      id: '/hq/funder/onboarding'
      path: '/hq/funder/onboarding'
      fullPath: '/hq/funder/onboarding'
      preLoaderRoute: typeof HqFunderOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/funder/organisations': {
      id: '/hq/funder/organisations'
      path: '/hq/funder/organisations'
      fullPath: '/hq/funder/organisations'
      preLoaderRoute: typeof HqFunderOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/funder/releases': {
      id: '/hq/funder/releases'
      path: '/hq/funder/releases'
      fullPath: '/hq/funder/releases'
      preLoaderRoute: typeof HqFunderReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/registry/': {
      id: '/hq/registry/'
      path: '/hq/registry'
      fullPath: '/hq/registry/'
      preLoaderRoute: typeof HqRegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/registry/api-clients': {
      id: '/hq/registry/api-clients'
      path: '/hq/registry/api-clients'
      fullPath: '/hq/registry/api-clients'
      preLoaderRoute: typeof HqRegistryApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/registry/api-usage': {
      id: '/hq/registry/api-usage'
      path: '/hq/registry/api-usage'
      fullPath: '/hq/registry/api-usage'
      preLoaderRoute: typeof HqRegistryApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/registry/bank-verification': {
      id: '/hq/registry/bank-verification'
      path: '/hq/registry/bank-verification'
      fullPath: '/hq/registry/bank-verification'
      preLoaderRoute: typeof HqRegistryBankVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/registry/claims': {
      id: '/hq/registry/claims'
      path: '/hq/registry/claims'
      fullPath: '/hq/registry/claims'
      preLoaderRoute: typeof HqRegistryClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/registry/operations': {
      id: '/hq/registry/operations'
      path: '/hq/registry/operations'
      fullPath: '/hq/registry/operations'
      preLoaderRoute: typeof HqRegistryOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/registry/records': {
      id: '/hq/registry/records'
      path: '/hq/registry/records'
      fullPath: '/hq/registry/records'
      preLoaderRoute: typeof HqRegistryRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveDemoRoute: LiveDemoRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatusRoute: StatusRoute,
  TrustRoute: TrustRoute,
  WalkthroughRoute: WalkthroughRoute,
  CheckoutSessionIdRoute: CheckoutSessionIdRoute,
  DocsApiRoute: DocsApiRoute,
  DocsApiPricingRoute: DocsApiPricingRoute,
  DocsAuthenticationRoute: DocsAuthenticationRoute,
  DocsCounterpartiesRoute: DocsCounterpartiesRoute,
  DocsErrorsRoute: DocsErrorsRoute,
  DocsEvidenceRoute: DocsEvidenceRoute,
  DocsMatchesRoute: DocsMatchesRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsWebhooksRoute: DocsWebhooksRoute,
  HqAiSuggestionsRoute: HqAiSuggestionsRoute,
  HqAuditRoute: HqAuditRoute,
  HqComplianceRoute: HqComplianceRoute,
  HqDisputesRoute: HqDisputesRoute,
  HqEngagementsRoute: HqEngagementsRoute,
  HqExecutionCasesRoute: HqExecutionCasesRoute,
  HqFacilitationRoute: HqFacilitationRoute,
  HqFunderWorkflowRoute: HqFunderWorkflowRoute,
  HqGovernanceRoute: HqGovernanceRoute,
  HqGovernanceRecordsRoute: HqGovernanceRecordsRoute,
  HqIdentityRoute: HqIdentityRoute,
  HqIdvRoute: HqIdvRoute,
  HqLegacyRepairRoute: HqLegacyRepairRoute,
  HqLegalHoldsRoute: HqLegalHoldsRoute,
  HqOrganisationsRoute: HqOrganisationsRoute,
  HqRevenueRoute: HqRevenueRoute,
  HqSettingsRoute: HqSettingsRoute,
  HqSystemHealthRoute: HqSystemHealthRoute,
  HqUsersRoute: HqUsersRoute,
  ProductsAuditLedgerRoute: ProductsAuditLedgerRoute,
  ProductsComplianceEngineRoute: ProductsComplianceEngineRoute,
  ProductsTradeDeskRoute: ProductsTradeDeskRoute,
  SolutionsFinanceRoute: SolutionsFinanceRoute,
  SolutionsSovereignsRoute: SolutionsSovereignsRoute,
  SolutionsTradersRoute: SolutionsTradersRoute,
  DocsIndexRoute: DocsIndexRoute,
  HqIndexRoute: HqIndexRoute,
  HqFunderAuditRoute: HqFunderAuditRoute,
  HqFunderOnboardingRoute: HqFunderOnboardingRoute,
  HqFunderOrganisationsRoute: HqFunderOrganisationsRoute,
  HqFunderReleasesRoute: HqFunderReleasesRoute,
  HqRegistryApiClientsRoute: HqRegistryApiClientsRoute,
  HqRegistryApiUsageRoute: HqRegistryApiUsageRoute,
  HqRegistryBankVerificationRoute: HqRegistryBankVerificationRoute,
  HqRegistryClaimsRoute: HqRegistryClaimsRoute,
  HqRegistryOperationsRoute: HqRegistryOperationsRoute,
  HqRegistryRecordsRoute: HqRegistryRecordsRoute,
  HqFunderIndexRoute: HqFunderIndexRoute,
  HqRegistryIndexRoute: HqRegistryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
